# Generated by Django 6.0.4 on 2026-05-01 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('IF', 'ID Front'), ('IB', 'ID Back'), ('DL', 'Driving License'), ('KR', 'KRA Pin'), ('LB', 'Logbook'), ('IN', 'Insurance'), ('PB', 'PSV Badge'), ('IP', 'Inspection Report')], max_length=2)),
                ('status', models.CharField(choices=[('PN', 'Pending'), ('VR', 'Verified'), ('RJ', 'Rejected'), ('EX', 'Expired')], max_length=2)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
