# Generated by Django 6.0.4 on 2026-06-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='object_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('PN', 'Pending'), ('VR', 'Verified'), ('RJ', 'Rejected'), ('EX', 'Expired')], default='PN', max_length=2),
        ),
    ]
