# Generated by Django 6.0.4 on 2026-05-01 11:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.carmake')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plate_number', models.CharField(max_length=30)),
                ('yom', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1975), django.core.validators.MaxValueValidator(2026)])),
                ('chasis_number', models.CharField(max_length=30)),
                ('engine_number', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=20)),
                ('valuation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('AV', 'Available'), ('FI', 'Financed'), ('OS', 'Out of Service'), ('IM', 'Immobilized')], default='AV', max_length=2)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.driverprofile')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.carmodel')),
            ],
        ),
    ]
